### ISSUE TITLE
Getting stuck after running 

### ISSUE THREAD

**Issue by MHassanSaeed** [TUM-Core-Facility-Microbiome/IMNGS2-Core-docs#9]
Hi all,
I get into a problem while trying to run the IMNGS2-Core. It gets stuck after binding the mount point.

A screenshot of the problem is attached.

Thank you very much.

![Screenshot 2024-05-16 172008](https://github.com/TUM-Core-Facility-Microbiome/IMNGS2-Core-docs/assets/109113145/9f1f535a-8f14-4ca4-9a36-197a43209479)

**Comment by zsewa** [comment]
Hi @MHassanSaeed, 
thanks for bringing this to our attention, and sorry for the inconvenience.

Could you please try moving your files to the C:// drive instead of having them on a different (detachable?) drive.
We are using WSL2 to execute the pipeline, which might be unreliable from time to time regarding mounting all available drives to the distribution.
